[MIG] website_sale_prod_description: Migration to 15.0
ingadhoc/website pull request #214
Opened 2021-12-10 17:45 UTC by JrAdhoc

2021-12-10 17:46 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/website/pull/214).

2022-08-03 14:55 UTC, nicomacr requested changes
@JrAdhoc Excellent Work.

Some details to fix below

2022-08-03 14:55 UTC, nicomacr commented on website_sale_prod_description/views/product_template_templates.xml
> +            <t t-if="len(product.description_website) > 1">
```suggestion
            <t t-if="not is_html_empty(product.description_website)">
```

2022-08-03 15:55 UTC, nicomacr commented
@roboadhoc r+

2022-08-03 15:55 UTC, nicomacr commented
@roboadhoc rebase-ff

2022-08-03 15:56 UTC, roboadhoc commented
Merge method set to rebase and fast-forward

2022-08-03 16:04 UTC, nicomacr approved these changes

2022-08-03 17:35 UTC, merged