[MIG] l10n_ar_website_sale_ux: Migration to 18.0
ingadhoc/website pull request #343
Opened 2024-11-14 19:19 UTC by ALopez-Adhoc

2024-11-14 19:20 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/343).

2024-11-22 17:48 UTC, zaoral requested changes
Hola @ALopez-Adhoc!
Como estas?
Muchas gracias por el PR

Te pido porfis si puedes hacer cambios
cualquier cosa estoy atenta

Saludos!

2024-11-22 17:48 UTC, zaoral commented on l10n_ar_website_sale_ux/__manifest__.py
> +    'installable': True,
```suggestion
    'installable': True,
    'auto_install' : ['l10n_ar_webiste_sale'],
```

2024-11-22 17:48 UTC, zaoral commented on l10n_ar_website_sale_ux/__manifest__.py
>      'license': 'AGPL-3',
Tocaría agregar la depende a l10n_ar_website_sale porque ahora esta en el auto install, y luego la dependencia de product quedo redundante, también la de l10n_ar. La de website_sale la dejamos porque modificamos vistas.
 
```python
    'depends': [
        'website_sale',
        'l10n_ar_website_sale',
    ],
```

2024-11-25 14:14 UTC, ALopez-Adhoc commented on l10n_ar_website_sale_ux/__manifest__.py
> +    'installable': True,
Listo el cambio!

2024-11-25 14:14 UTC, ALopez-Adhoc commented on l10n_ar_website_sale_ux/__manifest__.py
>      'license': 'AGPL-3',
Listo el cambio!

2024-12-11 16:38 UTC, zaoral commented
Superseded by https://github.com/ingadhoc/website/pull/346

2024-12-11 16:38 UTC, closed without merging