[REL] Migration website_security to V11.
ingadhoc/website pull request #63
Opened 2018-05-08 15:20 UTC by ValentinoDefelice

[FIX] Minor changes (odoo tags)
[FIX] Class name for new Odoo convention

2018-05-09 16:15 UTC, nicomacr requested changes
@ValentinoDefelice  in this line: https://github.com/adhoc-dev/website/blob/81e0d93c5e026a1f5133375839e903311011cb53/website_security/models/website.py#L14
Name of compute method should start with "_compute_"

2018-05-09 16:17 UTC, nicomacr requested changes
https://github.com/adhoc-dev/website/blob/81e0d93c5e026a1f5133375839e903311011cb53/website_security/models/website.py#L50
Api.one is deprecated

2018-05-09 16:18 UTC, nicomacr requested changes
same comment that the previous here https://github.com/adhoc-dev/website/blob/81e0d93c5e026a1f5133375839e903311011cb53/website_security/models/website.py#L30

2018-05-09 16:19 UTC, nicomacr commented on website_security/README.rst
> +#. Go to ...
remove this line

2018-05-10 13:21 UTC, jjscarafia commented on website_security/models/website.py
>      related_view_id = fields.Many2one(
Este campo no está andando. La idea de este campo es que los usuarios puedan ir rapidamente desde el menú a la vista para ver los permisos de la vista también.
Este campo sería mas sencillo para mi ahora, sería 
related_view_id = fields.Many2one(related='page_id.view_id')

Entender para que sirve el módulo y verificar que las cosas se usan y funcionan

2018-05-10 14:27 UTC, jjscarafia commented
además del comentario anterior hacer estos cambios de menus
![seleccion_398](https://user-images.githubusercontent.com/3016656/39874683-ddb0bb38-5444-11e8-8a88-8a23064ce5fa.png)

2018-05-11 20:51 UTC, merged