[REL] website_sale_product_descripion
ingadhoc/website pull request #72
Opened 2018-06-19 11:09 UTC by ValentinoDefelice

[FIX] Update models and views file names
[FIX] Update README

2018-06-19 12:33 UTC, zaoral approved these changes
+1

@ValentinoDefelice 
Please only need to fix a pylint error `website_sale_product_description/models/product_template.py:11:1: E303 too many blank lines (3)` https://travis-ci.org/ingadhoc/website/jobs/394054614#L828

2018-06-19 13:36 UTC, zaoral requested changes

2018-06-19 13:36 UTC, zaoral commented on website_sale_product_description/README.rst
> +#. Go to a Product, and you will see in 'Sale' page a 'Description for Website' title with a Description field.
> +#. Go to a Product, and you will see in 'Sale' page a 'Description for Website' title with a Description field.

change with 

> +#. Go to a Product, and you will see in 'Notes' page a 'Description for Website' text field

2018-06-19 13:36 UTC, zaoral commented on website_sale_product_description/models/product_template.py
>  _logger = logging.getLogger(__name__)
remove both _logger variable and import logging. this two are not necessary here

2018-06-19 13:36 UTC, zaoral commented on website_sale_product_description/models/product_template.py
we have a pylint error of two many empty lines, please fix this
https://travis-ci.org/ingadhoc/website/jobs/394054614#L828

2018-06-19 13:36 UTC, zaoral commented on website_sale_product_description/models/product_template.py
>      _inherit = 'product.template'
We have already a Sale Description field in the sale order. please update `description_website` field string to "Description for Website"

2018-06-19 13:36 UTC, zaoral commented on website_sale_product_description/views/product_template_views.xml
> +                <group>
* Currently it looks like this

  ![image](https://user-images.githubusercontent.com/7593953/41599733-6d3396a2-73aa-11e8-8317-7b8903cb16fd.png)

* Please make it look like this one 

  ![image](https://user-images.githubusercontent.com/7593953/41600038-31afff3e-73ab-11e8-98f1-93a7d01c97ee.png)

   - dont use separator, use group string instead
   - all the descriptions of the product are now in the Notes page, please move it to this section
   - Dont show the field label.

```xml
<group name="description" position="inside">
    <group string="Description for Website">
        <field name="description_website" nolabel="1" placeholder="Note to be displayed on e-commerce..."/>
    </group>
</group>
```

2018-06-19 15:25 UTC, nicomacr submitted a review, later dismissed
Hi @ValentinoDefelice for me it's OK the PR

2018-06-21 14:16 UTC, zaoral submitted a review, later dismissed

2018-06-25 14:58 UTC, merged